1.
ALTER TABLE visit DROP CONSTRAINT visit_owner

2.
ALTER TABLE visit DROP COLUMN email;
ALTER TABLE visit MODIFY name INT NOT NULL;

3.
ALTER TABLE visit ADD COLUMN test int UNSIGNED NOT NULL AFTER messageText, ADD CONSTRAINT UNIQUE UQ (`test`);

4.
ALTER TABLE visit DROP FOREIGN KEY visit_owner1
ADD CONSTRAINT visit_owner FOREIGN KEY(nameID) REFERENCES owners (ownerID) ON DELETE CASCADE